name: ci 
on:
    push:
        branches:
            - master
            - main
            - docs
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout docs
              uses: actions/checkout@v3
              with:
                ref: docs
            - name: Install Python
            - uses: actions/setup-python@v4
              with:
                python-version: 3.x
            - uses: actions/cache@v2
              with:
                key: ${{ github.ref }}
                path: .cache
            - name: build docs
              run: pip install mkdocs-material 
              run: mkdocs gh-deploy --force
