name: ci
on:
    workflow_dispatch:
    push:
        branches:
            - master
            - main
            - docs
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout docs
              uses: actions/checkout@v3
              with:
                ref: docs

            - name: Install Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.x

            - name: cache dependencies
              uses: actions/cache@v2
              with:
                key: ${{ github.ref }}
                path: .cache

            - name: build docs
              run: |
                pip install mkdocs-material
                npm install -g badge-maker
                TOKEN=${{ secrets.INSIGHTS_TOKEN }} python get_traffic.py
                mkdocs gh-deploy --force
